# Generated by Django 2.2.3 on 2019-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190905_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='1', max_length=1, verbose_name='是否在职'),
        ),
    ]
