# Generated by Django 2.2.3 on 2019-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190905_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='1', max_length=10, verbose_name='是否在职'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='isadmin',
            field=models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='0', max_length=10, verbose_name='是否管理员'),
        ),
    ]
